job: 
  name: latest
  dir: example

sumo:
  network: crossing.net.xml
  nogui: False
  demand:
    - vehicles:
      cyclist:
      pedestrians:
      pubilic:

tls:
  - id: 'C'
    logic_file:
    type:
    input:
      - feature: "count"
        user_type: "DEFAULT VEHTYPE"
        from: "phase"
        map:
          0: "A"
          2: "B"
    output:
    logging:

mpc:
  step: 5
  warmup: 1
  max_steps: 3000

logging:
  metrics: ["objective", "state"]